// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

import "github.com/aws-cloudformation/cloudformation-cli-go-plugin/cfn/handler"

// TypeConfiguration is autogenerated from the json schema
type TypeConfiguration struct {
	ConjurAPIURL                  *string                        `json:",omitempty"`
	ConjurAuthenticatorProperties *ConjurAuthenticatorProperties `json:",omitempty"`
	PAMAccessProperties           *PAMAccessProperties           `json:",omitempty"`
}

// ConjurAuthenticatorProperties is autogenerated from the json schema
type ConjurAuthenticatorProperties struct {
	ConjurIdentity      *string `json:",omitempty"`
	ConjurAuthenticator *string `json:",omitempty"`
	ConjurAccount       *string `json:",omitempty"`
	ConjurAWSRegion     *string `json:",omitempty"`
	ConjurIAMRoleARN    *string `json:",omitempty"`
}

// PAMAccessProperties is autogenerated from the json schema
type PAMAccessProperties struct {
	IDTenantURL  *string `json:",omitempty"`
	UserKey      *string `json:",omitempty"`
	PassKey      *string `json:",omitempty"`
	PcloudURLKey *string `json:",omitempty"`
}

// Configuration returns a resource's configuration.
func Configuration(req handler.Request) (*TypeConfiguration, error) {
	// Populate the type configuration
	typeConfig := &TypeConfiguration{}
	if err := req.UnmarshalTypeConfig(typeConfig); err != nil {
		return typeConfig, err
	}
	return typeConfig, nil
}
