// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	SafeName                  *string               `json:",omitempty"`
	PlatformID                *string               `json:",omitempty"`
	Name                      *string               `json:",omitempty"`
	Address                   *string               `json:",omitempty"`
	UserName                  *string               `json:",omitempty"`
	Secret                    *string               `json:",omitempty"`
	SecretType                *string               `json:",omitempty"`
	SecretManagement          *SecretManagement     `json:",omitempty"`
	PlatformAccountProperties []KVpair              `json:",omitempty"`
	RemoteMachinesAccess      *RemoteMachinesAccess `json:",omitempty"`
	AccountResourceId         *string               `json:",omitempty"`
}

// SecretManagement is autogenerated from the json schema
type SecretManagement struct {
	AutomaticManagementEnabled *bool   `json:",omitempty"`
	ManualManagementReason     *string `json:",omitempty"`
}

// KVpair is autogenerated from the json schema
type KVpair struct {
	Key   *string `json:",omitempty"`
	Value *string `json:",omitempty"`
}

// RemoteMachinesAccess is autogenerated from the json schema
type RemoteMachinesAccess struct {
	RemoteMachines                   *string `json:",omitempty"`
	AccessRestrictedToRemoteMachines *bool   `json:",omitempty"`
}
